---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-metadata
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: konflux
spec:
  results:
    - name: job-spec
      description: The konflux ci job spec metadata generated.
    - name: prefetch-artifact
      description: The OCI artifact that contains the prefetch dependencies generated during the build phase.
  params:
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test.
    - name: test-name
      type: string
      description: The name of the test being executed.
    - name: enable-prefetch
      type: string
      description: Flag to indicate whether to retrieve the OCI artifact associated with the prefetching operation from the build phase. If set to "true", the artifact's digest will be fetched.
      default: "false"
  steps:
    - name: test-metadata
      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
      workingDir: /workspace
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: ENABLE_PREFETCH
          value: $(params.enable-prefetch)
        - name: EVENT_TYPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/event-type']
        - name: KONFLUX_COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: PULL_REQUEST_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/pull-request']
        - name: GIT_ORGANIZATION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/url-org']
        - name: GIT_REPOSITORY
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pac.test.appstudio.openshift.io/url-repository']
        - name: SOURCE_REPO_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/source-repo-url']
        - name: SOURCE_REPO_BRANCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/source-branch']
        # This value refers to the target branch value in 'pull-request' events and branch value in 'push' events.
        # E.g. for push event to 'main' branch this will have the value 'main'. For PR event that targets 'main' branch, this will be also 'main'.
        - name: TARGET_REPO_BRANCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/branch']
      script: |
        #!/bin/bash

        # Extract additional environment variables from SNAPSHOT
        GIT_URL=$(jq -r --arg component_name "$KONFLUX_COMPONENT_NAME" '.components[] | select(.name == $component_name) | .source.git.url' <<< "$SNAPSHOT")
        GIT_REVISION=$(jq -r --arg component_name "$KONFLUX_COMPONENT_NAME" '.components[] | select(.name == $component_name) | .source.git.revision' <<< "$SNAPSHOT")
        SOURCE_REPO_ORG=$(echo "$SOURCE_REPO_URL" | sed -E 's#https://github.com/([^/]+)/.*#\1#')

        PR_AUTHOR="$(curl -s https://api.github.com/repos/${GIT_ORGANIZATION}/${GIT_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER} | jq -r .user.login)"

        COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "$KONFLUX_COMPONENT_NAME" '.components[] | select(.name == $component_name) | .containerImage' <<< "$SNAPSHOT")

        if [[ "$EVENT_TYPE" != "push" && -n "$PULL_REQUEST_NUMBER" ]]; then
          EVENT_TYPE="pull_request"
        elif [[ -z "$PULL_REQUEST_NUMBER" && "$EVENT_TYPE" != "push" ]]; then
          EVENT_TYPE="push"
        fi

        JOB_SPEC=$(cat <<EOF
        {
            "container_image": "$COMPONENT_CONTAINER_IMAGE",
            "konflux_component": "$KONFLUX_COMPONENT_NAME",
            "snapshot": $SNAPSHOT,
            "git": {
                "pull_request_number": $PULL_REQUEST_NUMBER,
                "pull_request_author": "$PR_AUTHOR",
                "org": "$GIT_ORGANIZATION",
                "repo": "$GIT_REPOSITORY",
                "commit_sha": "$GIT_REVISION",
                "event_type": "$EVENT_TYPE",
                "source_repo_url": "$SOURCE_REPO_URL",
                "source_repo_org": "$SOURCE_REPO_ORG",
                "source_repo_branch": "$SOURCE_REPO_BRANCH",
                "target_repo_branch": "$TARGET_REPO_BRANCH",
                "url": "$GIT_URL",
                "revision": "$GIT_REVISION"
            }
        }
        EOF
        )

        echo "[INFO] Job spec:"
        echo "$JOB_SPEC"

        # Write job-spec to result file
        echo -n "$JOB_SPEC" > $(results.job-spec.path)

        if [ "$ENABLE_PREFETCH" == "true" ]; then

          cosign download attestation "$COMPONENT_CONTAINER_IMAGE" > cosign_metadata.json

          CACHI2_SOURCE_ARTIFACT="$(jq -r \
            '.payload | @base64d | fromjson | .predicate.buildConfig.tasks[] |
            select(.name == "prefetch-dependencies") | .results[] | select(.name == "CACHI2_ARTIFACT") | .value' \
            cosign_metadata.json)"

          echo "[INFO] Cachi2 source artifact: $CACHI2_SOURCE_ARTIFACT"

          echo -n "$CACHI2_SOURCE_ARTIFACT" > $(results.prefetch-artifact.path)

        fi
