name: Hadolint

"on":
  pull_request:
    branches: [main]
    paths:
      - "**/Dockerfile*"
      - ".hadolint.yaml"
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Run Hadolint on Dockerfiles
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          recursive: true
          config: .hadolint.yaml
